language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
    - riak
    - mongodb
    - memcached
    - redis-server

before_script: 
    - pecl install riak
    - composer self-update
    - composer --prefer-source --dev install
    - phpenv config-add ./Tests/travis/php.ini

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs -np --extensions=php --ignore=vendor/*,Tests/* --standard=ruleset.xml .
after_script:
    - php ./vendor/bin/coveralls -v
